### ISSUE TITLE
-- Not an issue, more question --- calling form 

### ISSUE THREAD

**Issue by lexandclo** [tony13tv/silverstripe-registration#1]
Hi
Ive added this via composer, how do i go about calling the registration form on my page and setting a redirect after signing up ?

Thanks in advance

Darren

**Comment by tony13tv** [comment]
Hi,

It actually goes to whatever your config.yml is set to:
```
Silverstripe\Security:
  - default_login_dest: '/account/index'
```
I will be introducing a new `default_registration_dest` config key for this purpose.

**Comment by tony13tv** [comment]
I already checked the code and registration form already goes to the route configured in default_registration_dest. I'm closing this issue.
